package auth

// Embedded Ed25519 public keys for verifying Kilometers API signatures
// These keys match the Ed25519 configuration in the API's appsettings.Development.json

const (
	// PrimaryKeyID is the current primary key identifier
	PrimaryKeyID = "key-001"

	// RotationKeyID is the key used during rotation periods
	RotationKeyID = "key-000"

	// PublicKeyPrimary is the current primary Ed25519 public key (base64-encoded raw format)
	// This key corresponds to "key-001" generated by the API
	PublicKeyPrimary = "EnK5qSf2n7zrgO2axsOJ5zaDeUsuY5t02cNPkgRR2+4="

	// PublicKeyRotation is the previous key for rotation support
	// This would be populated during key rotation periods
	PublicKeyRotation = "" // Empty for now - will be populated during first key rotation
)

// EmbeddedPublicKeys is a map of key IDs to their corresponding public keys
var EmbeddedPublicKeys = map[string]string{
	PrimaryKeyID:  PublicKeyPrimary,
	RotationKeyID: PublicKeyRotation,
}

// Key metadata for reference
const (
	// KeyAlgorithm specifies the signature algorithm
	KeyAlgorithm = "EdDSA"

	// KeyCurve specifies the elliptic curve
	KeyCurve = "Ed25519"

	// KeyUse specifies the intended use
	KeyUse = "sig"
)
